name: Hexo-CI

on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: hexo
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Deploy Key Config
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${{ACTION_DEPLOY_KEY}} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Git Config  
        run: |
          git config --global user.email "liwei2633@163.com"
          git config --global user.name "monkeyWie"
      - name: Install
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install
      - name: Hexo Deploy
        run: |
          hexo clean
          hexo d
